//
//  ControlAuditSelfQA.swift — walks the interface and reports what actually works.
//
//  Purpose : "Is every switch wired up?" should not be answered by looking. This
//            builds the whole window offscreen, walks the view tree, and reports
//            every control with whether it is enabled and whether it has a target
//            and action — so a control that looks live but does nothing is caught
//            mechanically rather than during a show.
//  Inputs  : none; it constructs its own ShellView.
//  Outputs : selfqa/out/audit/controls.md — a table, and a TODO list of everything
//            disabled, ready to paste into docs.
//  Connects: ShellView and every panel beneath it.
//
//  A control counts as WIRED when it is enabled and has both a target and an action,
//  or is one of the custom controls that carries its own behaviour. Anything enabled
//  with no action is the dangerous case: it looks live and does nothing.
//

import AppKit
import VideoboyCore

/// Audits the interface's controls.
enum ControlAuditSelfQA {

    /// One control found in the tree.
    private struct Finding {
        let panel: String
        let kind: String
        let label: String
        let isEnabled: Bool
        let hasAction: Bool

        /// Enabled and connected to something.
        var isLive: Bool { isEnabled && hasAction }
        /// Enabled but connected to nothing — looks usable, does nothing.
        var isDeceptive: Bool { isEnabled && !hasAction }
    }

    static func run() -> SelfQAVerdict {
        let check = SelfQACheck(name: "audit")

        // Build the shell AND its controller, exactly as the app does. Auditing a
        // bare ShellView would report every controller-wired control as dead, which
        // is worse than not auditing at all — it would send you hunting for bugs
        // that are artefacts of how the audit was built.
        let shell = ShellView()
        let engine = Engine()
        let controller = ShellController(shell: shell, engine: engine)
        shell.frame = NSRect(x: 0, y: 0, width: 1460, height: 912)
        shell.layoutSubtreeIfNeeded()
        // Keep the controller alive for the walk; it owns the wiring being audited.
        withExtendedLifetime(controller) {}

        var findings: [Finding] = []
        collect(from: shell, panel: "window", into: &findings)

        let live = findings.filter(\.isLive)
        let disabled = findings.filter { !$0.isEnabled }
        let deceptive = findings.filter(\.isDeceptive)

        check.note("\(findings.count) controls found: \(live.count) live, \(disabled.count) disabled, \(deceptive.count) enabled-but-unwired")

        // Write the report.
        var lines: [String] = []
        lines.append("# Control audit")
        lines.append("")
        lines.append("Generated by `Videoboy --selfqa audit`. Do not edit by hand — re-run it.")
        lines.append("")
        lines.append("| State | Count |")
        lines.append("|---|---|")
        lines.append("| Live (enabled, wired) | \(live.count) |")
        lines.append("| Disabled (labelled not-yet-built) | \(disabled.count) |")
        lines.append("| **Enabled but unwired** | **\(deceptive.count)** |")
        lines.append("| Total | \(findings.count) |")
        lines.append("")

        if !deceptive.isEmpty {
            lines.append("## Enabled but unwired — these look usable and do nothing")
            lines.append("")
            for finding in deceptive.sorted(by: { $0.panel < $1.panel }) {
                lines.append("- `\(finding.panel)` — \(finding.kind) \"\(finding.label)\"")
            }
            lines.append("")
        }

        lines.append("## Disabled — present, visibly inert, waiting on their feature")
        lines.append("")
        for finding in disabled.sorted(by: { $0.panel < $1.panel }) {
            lines.append("- `\(finding.panel)` — \(finding.kind) \"\(finding.label)\"")
        }
        lines.append("")
        lines.append("## Live")
        lines.append("")
        for finding in live.sorted(by: { $0.panel < $1.panel }) {
            lines.append("- `\(finding.panel)` — \(finding.kind) \"\(finding.label)\"")
        }

        let report = lines.joined(separator: "\n") + "\n"
        do {
            try report.write(to: check.artifactURL("controls.md"), atomically: true, encoding: .utf8)
            Log.info(.selfqa, "wrote control audit -> \(check.artifactURL("controls.md").path)")
        } catch {
            Log.error(.selfqa, "could not write the control audit: \(error)")
        }

        // The failing condition is a control that is enabled and wired to nothing.
        // A disabled control is fine — it is honest about not being built.
        check.record(AssertionResult(
            name: "no control is enabled but unwired",
            passed: deceptive.isEmpty,
            detail: deceptive.isEmpty
                ? "every enabled control has an action"
                : "\(deceptive.count): " + deceptive.map { "\($0.panel)/\($0.label)" }.joined(separator: ", ")
        ))
        check.record(AssertionResult(
            name: "the interface has controls at all",
            passed: findings.count > 40,
            detail: "\(findings.count) found"
        ))

        return check.finish()
    }

    /// Walks the view tree, recording controls and the panel each sits in.
    private static func collect(from view: NSView, panel: String, into findings: inout [Finding]) {
        var currentPanel = panel
        if let panelView = view as? PanelView {
            currentPanel = panelView.title
        }

        for subview in view.subviews {
            if let control = subview as? NSControl {
                findings.append(describe(control, panel: currentPanel))
                // A control's own subviews are its internals, not more controls.
                continue
            }
            collect(from: subview, panel: currentPanel, into: &findings)
        }
    }

    /// Turns a control into a finding.
    private static func describe(_ control: NSControl, panel: String) -> Finding {
        let kind: String
        var label = ""

        switch control {
        case let button as NSButton:
            kind = "button"
            label = button.title.isEmpty ? (button.toolTip ?? "untitled") : button.title
        case let popUp as NSPopUpButton:
            kind = "popup"
            label = popUp.itemTitles.first ?? "empty"
        case let segmented as NSSegmentedControl:
            kind = "segmented"
            label = (0..<segmented.segmentCount)
                .compactMap { segmented.label(forSegment: $0) }
                .joined(separator: "/")
        case is NSSwitch:
            kind = "switch"
            label = control.toolTip ?? "toggle"
        case let fader as VBFader:
            kind = "fader"
            label = fader.identifier?.rawValue ?? "unnamed"
        case is NSSearchField:
            kind = "search"
            label = (control as? NSSearchField)?.placeholderString ?? "search"
        case is RecordButton:
            kind = "record"
            label = "record"
        case is MiniRecordIndicator:
            kind = "arm"
            label = (control as? MiniRecordIndicator)?.label ?? "arm"
        case is CollapsedRailView:
            kind = "rail"
            label = (control as? CollapsedRailView)?.title ?? "rail"
        case is NSTextField:
            // Labels are NSControls too, and are not interactive.
            kind = "label"
            label = (control as? NSTextField)?.stringValue ?? ""
        default:
            kind = String(describing: type(of: control))
            label = control.toolTip ?? ""
        }

        // Labels are not controls for this purpose.
        if kind == "label" {
            return Finding(panel: panel, kind: kind, label: label, isEnabled: false, hasAction: true)
        }

        return Finding(
            panel: panel,
            kind: kind,
            label: label,
            isEnabled: control.isEnabled,
            hasAction: control.action != nil && control.target != nil
        )
    }
}
