//
//  AmigaSideScripts.swift — the half of the link that runs on the Amiga.
//
//  Purpose : `AmigaCommandBridge` writes command files into a shared drawer. Something
//            on the Amiga has to read them and hand them to Scala's ARexx port. That
//            something is generated here, as text, and written into the drawer
//            alongside the commands.
//  Inputs  : the volume name the drawer is mounted as, and the program's port name.
//  Outputs : ARexx and AmigaDOS source, as strings.
//  Connects: AmigaCommandBridge (the near end), FSUAEConfiguration (which mounts the
//            drawer), scripts/setup-amiga.sh (which writes these out).
//  Extend  : a program with a different port is a different `portName` — the listener
//            itself does not care what it is forwarding.
//
//  ── WHY THE SCRIPT IS GENERATED AND NOT A FILE IN THE REPO ──────────────────────
//
//  Because it has to agree with the Swift side about four things — the drawer names,
//  the file extensions, the acknowledgement format, and the port — and two files that
//  must agree are two files that will eventually disagree. Generating it means the
//  constants exist once. It also means the tests can assert on the ACTUAL script that
//  ships rather than on a copy of it.
//
//  ── ON WRITING AREXX IN 2026 ────────────────────────────────────────────────────
//
//  Three things about ARexx that this depends on and that are easy to get wrong:
//
//  1. `ADDRESS <host> <expression>` sends ONE command to that host without changing
//     the current host. That is what forwards a line whose text is only known at
//     runtime. The alternative — setting the host and then writing a bare variable —
//     works too, but reads like a typo and invites someone to "fix" it.
//  2. `delay()`, `exists()` and friends live in `rexxsupport.library`, which must be
//     added with `addlib` before first use. Without it the script dies on line one.
//  3. AmigaDOS pattern matching is `#?`, not `*`.
//

import Foundation

/// The scripts that run inside the emulated machine.
public enum AmigaSideScripts {

    /// The Amiga volume the shared drawer is mounted as.
    ///
    /// Short and unlikely to collide. AmigaDOS volume names end in a colon when used,
    /// so this is stored without one and joined where needed.
    public static let volumeName = "VB"

    /// How often the listener looks for new commands, in Amiga ticks (50 per second).
    ///
    /// Ten ticks is five times a second. Deliberately slower than the host's twenty
    /// flushes a second: the host coalesces, so a slower reader simply takes a slightly
    /// larger batch each time, which is CHEAPER on a 68k than polling faster. A tighter
    /// loop would spend the machine's time on directory scans instead of on Scala.
    public static let pollTicks = 10

    /// The ARexx listener.
    ///
    /// Reads command files oldest-first, forwards each line to the program's port,
    /// deletes the file, and writes an acknowledgement the host uses to light its link
    /// indicator.
    ///
    /// ── NO `ADDRESS COMMAND` ANYWHERE IN HERE, DELIBERATELY ─────────────────────
    ///
    /// The first version listed the drawer by shelling out:
    /// `address command 'list > T:vblink.lst ...'`. It is the idiom the disc's own
    /// example uses, and on this machine it fails outright:
    ///
    ///     +++ Error 13 in line 60: Host environment not found
    ///
    /// AROS's ARexx has no COMMAND host. Rather than require a particular Kickstart
    /// for the LISTENER — the one part that has to work before anything else can be
    /// diagnosed — this uses `showdir()` and `delete()` from rexxsupport.library
    /// instead. No shell, no temporary file, no dependency on which ARexx is running.
    /// It is simpler than the version that needed a working shell, which is the usual
    /// shape of this kind of fix.
    public static func listener(portName: String = ScalaLingo.portName) -> String {
        """
        /* VBLink.rexx - Videoboy's link into \(portName).
         *
         * GENERATED by AmigaSideScripts.swift. Edit that, not this.
         *
         * Watches \(volumeName):cmd for files ending .vbc, sends each line inside them
         * to the \(portName) port, deletes the file, and drops a matching .ack into
         * \(volumeName):ack so the host knows the machine is listening.
         *
         * Run it with:  rx \(volumeName):VBLink.rexx
         */

        options results
        options failat 21

        /* showdir(), delete() and delay() live here. Everything below needs them. */
        if ~show('L', 'rexxsupport.library') then
            if ~addlib('rexxsupport.library', 0, -30, 0) then do
                say 'VBLink: cannot open rexxsupport.library'
                exit 20
            end

        cmddir = '\(volumeName):cmd'
        ackdir = '\(volumeName):ack'
        port   = '\(portName)'

        say 'VBLink: watching' cmddir 'for' port

        /* A heartbeat the HOST can read. Redirecting this script's console output to a
         * file was the first attempt and it does not survive: ARexx buffers, so the
         * file stays empty until the script exits, which is exactly never for a loop
         * like this one. A file the script writes itself is flushed when it is closed,
         * every time round. */
        call heartbeat('starting')

        beats = 0
        do forever
            call delay(\(pollTicks))

            /* Roughly every two seconds. Often enough for a link light to be
             * trustworthy, rare enough not to be writing to disk in a tight loop. */
            beats = beats + 1
            if beats // 10 = 0 then
                call heartbeat('alive')

            listing = showdir(cmddir, 'F', ' ')
            if listing = '' then iterate

            /* Keep only the command files. Anything else in the drawer is ours and
             * none of this loop's business. */
            n = 0
            do i = 1 to words(listing)
                nm = word(listing, i)
                if right(nm, 4) = '.vbc' then do
                    n = n + 1
                    names.n = nm
                end
            end
            if n = 0 then iterate

            /* Oldest first. The names are zero-padded sequence numbers, so sorting
             * them alphabetically IS sorting them by age - which is the whole reason
             * they are zero-padded. An insertion sort is right here: n is a handful,
             * and this has to be legible on a machine with no debugger. */
            do i = 2 to n
                key = names.i
                j = i - 1
                do while j > 0
                    if names.j <= key then leave
                    k = j + 1
                    names.k = names.j
                    j = j - 1
                end
                k = j + 1
                names.k = key
            end

            do i = 1 to n
                call runfile(names.i)
            end
        end

        exit 0

        /* Send one command file's lines, then clear it and acknowledge. */
        runfile:
            parse arg fname
            full = cmddir || '/' || fname

            if ~open('cmd', full, 'Read') then
                return 0

            /* Check the port ONCE per file rather than per line: it cannot appear
             * halfway through a batch, and asking is not free. */
            havePort = show('P', port)

            /* HOLD, do not drop. The program takes some twenty seconds to boot and
             * open its port, and the host sends the whole panel the moment the machine
             * starts - so the batch that opens the screen and puts up the first line of
             * text arrives BEFORE there is anything to receive it. Dropping it left the
             * machine sitting on the boot console for ever, with the port open, the
             * link alive and nothing on screen, because nothing ever told it to draw.
             *
             * Leaving the file in place costs nothing: the poll comes round again, the
             * files are processed oldest first, and the batch lands the moment the port
             * appears - in the right order, because a held file blocks the ones behind
             * it, which is exactly what SCREEN-before-TEXT needs. */
            if ~havePort then do
                call close('cmd')
                call heartbeat('waiting for' port)
                return 0
            end

            /* Record what the PROGRAM said, not just that we spoke. Without this the
             * link reports "ok" whether Scala ran the command or refused every one of
             * them, which is exactly the state that wasted an afternoon: port open,
             * every command acknowledged, nothing on screen. rc is the program's
             * answer; anything non-zero goes into the acknowledgement with the line
             * that caused it. */
            failures = ''
            sent = 0
            do while ~eof('cmd')
                ln = readln('cmd')
                if length(strip(ln)) > 0 then do
                    address value port
                    options results
                    ln
                    sent = sent + 1
                    if rc ~= 0 then
                        failures = failures || 'rc=' || rc || ' <- ' || strip(ln) || '0a'x
                end
            end
            call close('cmd')

            /* Delete BEFORE acknowledging. If the machine dies between the two the
             * host merely re-sends state it already sent, which is harmless; the other
             * order would replay the command forever. */
            call delete(full)

            seq = fname
            if right(seq, 4) = '.vbc' then
                seq = left(seq, length(seq) - 4)

            /* The acknowledgement now carries the program's own answer: "ok" with a
             * count when every line was accepted, "REFUSED" with the return code and
             * the offending line when it was not. A batch that has not been delivered
             * yet is not acknowledged at all - it is still sitting in the drawer. */
            if open('ack', ackdir || '/' || seq || '.ack', 'Write') then do
                if failures = '' then
                    call writeln('ack', 'ok' sent 'sent')
                else do
                    call writeln('ack', 'REFUSED' sent 'sent')
                    call writech('ack', failures)
                end
                call close('ack')
            end
        return 0

        /* Say we are here, and whether the program's port is open. Two different
         * facts, and telling them apart is most of diagnosing this link. */
        heartbeat:
            parse arg what
            if open('hb', ackdir || '/link.status', 'Write') then do
                call writeln('hb', what)
                if show('P', port) then
                    call writeln('hb', 'port open')
                else
                    call writeln('hb', 'port closed')
                call close('hb')
            end
        return 0
        """
    }

    /// The AmigaDOS script that starts everything, for `S/User-Startup`.
    ///
    /// Started in this order for a reason: ARexx has to be up before anything can open
    /// a port, Scala has to be up before the listener has somewhere to forward to, and
    /// the listener last so it never forwards into a port that is not there yet.
    public static func startup(scalaPath: String) -> String {
        """
        ; Videoboy — starts ARexx, Scala and the command listener.
        ; GENERATED by AmigaSideScripts.swift.

        ; 1. ARexx itself. Nothing below works without it, and it takes a moment to
        ;    open its port, hence the wait.
        Assign RexxMast: SYS:System
        Run >NIL: SYS:System/RexxMast
        Wait 3

        ; 2. Scala. Run rather than executed inline so the script continues.
        Run >NIL: \(scalaPath)
        Wait 10

        ; 3. The listener, which forwards whatever the host sends.
        Run >NIL: rx \(volumeName):VBLink.rexx
        """
    }

    /// A one-line ARexx probe that answers "is the port there".
    ///
    /// Useful on its own: it is the difference between "Scala has not finished loading"
    /// and "Scala is not running", which are the same silence from outside.
    public static func portProbe(portName: String = ScalaLingo.portName) -> String {
        """
        /* VBProbe.rexx — reports whether \(portName) is open. */
        if show('P', '\(portName)') then do
            say 'open'
            exit 0
        end
        say 'closed'
        exit 5
        """
    }

    /// Folds text down to plain ASCII.
    ///
    /// The Amiga predates Unicode entirely, and these files are written as ISO Latin-1.
    /// An em dash or a curly quote in a COMMENT is enough to fail the whole write —
    /// which is exactly what happened the first time this ran. Folding at the source
    /// beats a lossy encode at the destination, because lossy encoding turns the
    /// characters into `?` inside a script the Amiga then has to read.
    public static func asciiFolded(_ text: String) -> String {
        var folded = text
        for (from, to) in [
            ("\u{2014}", "-"), ("\u{2013}", "-"), ("\u{2026}", "..."),
            ("\u{201C}", "\""), ("\u{201D}", "\""),
            ("\u{2018}", "'"), ("\u{2019}", "'"),
            ("\u{00D7}", "x"), ("\u{00A0}", " ")
        ] {
            folded = folded.replacingOccurrences(of: from, with: to)
        }
        // Anything still outside ASCII is dropped rather than guessed at.
        return String(folded.unicodeScalars.filter { $0.isASCII })
    }

    /// A stand-in for the real program: opens its port and writes down what arrives.
    ///
    /// ── WHY THIS IS NOT JUST A TEST FIXTURE ─────────────────────────────────────
    ///
    /// The chain is: fader -> command -> file -> listener -> ARexx port -> program. Six
    /// links. When the last one will not run — Scala's `scalamm.gfx` device does not
    /// load under AROS — every link before it becomes unverifiable too, and "nothing
    /// happens" is the same symptom whether the wire is broken or the program is.
    ///
    /// This opens the port the program WOULD open and appends everything sent to it to
    /// a log file in the shared drawer, where the host can read it back. That turns
    /// five of the six links into something with an answer, and leaves exactly one
    /// unknown instead of six.
    ///
    /// It is also how the panel gets developed on a machine with no Kickstart, which is
    /// most of them.
    public static func portEcho(portName: String = ScalaLingo.portName) -> String {
        """
        /* VBEcho.rexx - answers on \(portName) and writes down what it is told.
         *
         * GENERATED by AmigaSideScripts.swift.
         *
         * A stand-in for the real program, so the link can be proved end to end on a
         * machine where the real program will not start. Everything sent to the port is
         * appended to \(volumeName):ack/echo.log, which the host reads back.
         *
         * Run it with:  rx \(volumeName):VBEcho.rexx
         */

        options results

        if ~show('L', 'rexxsupport.library') then
            if ~addlib('rexxsupport.library', 0, -30, 0) then do
                say 'VBEcho: cannot open rexxsupport.library'
                exit 20
            end

        port = '\(portName)'
        logfile = '\(volumeName):ack/echo.log'

        if show('P', port) then do
            say 'VBEcho:' port 'is already open - the real program must be running'
            exit 5
        end

        if ~openport(port) then do
            say 'VBEcho: could not open' port
            exit 10
        end

        say 'VBEcho: answering on' port

        do forever
            call waitpkt(port)
            pkt = getpkt(port)
            /* A null packet means the wait was woken with nothing behind it. */
            if pkt = '0000 0000'x then iterate

            cmd = getarg(pkt)
            /* Reply FIRST. The sender is blocked until this happens, and a sender
             * blocked on a log write is a machine that appears to have hung. */
            call reply(pkt, 0)

            /* Append, falling back to Write. ARexx's 'Append' will not create a
             * file that is not there yet, so the very first command would otherwise
             * be the one that silently vanishes. */
            opened = open('log', logfile, 'Append')
            if ~opened then
                opened = open('log', logfile, 'Write')
            if opened then do
                call writeln('log', cmd)
                call close('log')
            end
        end

        call closeport(port)
        exit 0
        """
    }

    /// Everything that has to be written into the shared drawer, by file name.
    ///
    /// One function so the setup script and the tests cannot disagree about what a
    /// complete installation contains.
    public static func drawerContents(
        portName: String = ScalaLingo.portName,
        scalaPath: String = "Work:Scala/ScalaMM"
    ) -> [String: String] {
        [
            "VBLink.rexx": asciiFolded(listener(portName: portName)),
            "VBProbe.rexx": asciiFolded(portProbe(portName: portName)),
            "VBEcho.rexx": asciiFolded(portEcho(portName: portName)),
            "VBStartup": asciiFolded(startup(scalaPath: scalaPath))
        ]
    }
}
