#!/usr/bin/env bash
#
# make-fixtures.sh — generate the synthetic sample media the tests need.
#
# Purpose : Phase 1 and 2 need a genuine DV bitstream (real DIF blocks, real DCT
#           coefficients) to demux, decode and corrupt. This generates one, plus a
#           couple of ordinary clips, so the repo is self-sufficient.
# Inputs  : the ffmpeg CLI (a build-time developer tool only — it is NOT linked
#           into the app; see docs/THIRD-PARTY.md for the app's own libav).
# Outputs : samples/*.dv, samples/*.mov, samples/manifest.json.
# Note    : These are synthetic stand-ins. Real-world DV off tape has artefacts no
#           encoder reproduces, so the human's own footage is still wanted for
#           aesthetic work — see docs/BLOCKED.md.
source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

SAMPLES="$REPO_ROOT/samples"
mkdir -p "$SAMPLES"

command -v ffmpeg >/dev/null 2>&1 || fail "ffmpeg CLI not found; install it (brew install ffmpeg) to generate fixtures"

# NTSC DV: 720x480, 29.97, 120000 bytes per frame. `-target ntsc-dv` pins all of it.
if [ ! -f "$SAMPLES/bars.dv" ]; then
  log "generating samples/bars.dv (SMPTE bars, 4s NTSC DV)"
  ffmpeg -y -loglevel error \
    -f lavfi -i "smptebars=size=720x480:rate=30000/1001:duration=4" \
    -f lavfi -i "sine=frequency=440:sample_rate=48000:duration=4" \
    -target ntsc-dv "$SAMPLES/bars.dv"
fi

# Moving content matters: a static picture cannot show whether playback advances,
# and cannot distinguish a dropped frame from a held one.
if [ ! -f "$SAMPLES/motion.dv" ]; then
  log "generating samples/motion.dv (moving test source, 6s NTSC DV)"
  ffmpeg -y -loglevel error \
    -f lavfi -i "testsrc2=size=720x480:rate=30000/1001:duration=6" \
    -f lavfi -i "sine=frequency=220:sample_rate=48000:duration=6" \
    -target ntsc-dv "$SAMPLES/motion.dv"
fi

# An ordinary file for the AVFoundation path, which handles everything that is not DV.
if [ ! -f "$SAMPLES/motion.mov" ]; then
  log "generating samples/motion.mov (H.264, 6s)"
  ffmpeg -y -loglevel error \
    -f lavfi -i "testsrc2=size=720x480:rate=30000/1001:duration=6" \
    -c:v libx264 -pix_fmt yuv420p -crf 18 "$SAMPLES/motion.mov"
fi

log "writing samples/manifest.json"
python3 - "$SAMPLES" <<'PY'
import json, os, sys

samples_dir = sys.argv[1]
# DV frames are fixed-size, so a byte count is an exact frame count. 120000 bytes
# is one NTSC DV frame at 25 Mbit/s (SPEC 5).
NTSC_DV_FRAME_BYTES = 120000

entries = []
for name in sorted(os.listdir(samples_dir)):
    path = os.path.join(samples_dir, name)
    if name.startswith('.') or not os.path.isfile(path) or name == 'manifest.json':
        continue
    extension = os.path.splitext(name)[1].lower().lstrip('.')
    if extension not in ('dv', 'mov', 'mp4', 'm2v', 'mpg'):
        continue
    size = os.path.getsize(path)
    entry = {
        'file': name,
        'kind': 'dv' if extension == 'dv' else 'standard',
        'bytes': size,
        'origin': 'generated by scripts/make-fixtures.sh (synthetic)',
    }
    if extension == 'dv':
        entry['frameBytes'] = NTSC_DV_FRAME_BYTES
        entry['frameCount'] = size // NTSC_DV_FRAME_BYTES
        entry['standard'] = 'NTSC'
        entry['width'] = 720
        entry['height'] = 480
    entries.append(entry)

manifest = {
    'note': 'Generated by scripts/make-fixtures.sh. Drop real media in samples/ and re-run to include it.',
    'samples': entries,
}
with open(os.path.join(samples_dir, 'manifest.json'), 'w') as handle:
    json.dump(manifest, handle, indent=2, sort_keys=True)
    handle.write('\n')
print(f'  {len(entries)} sample(s) indexed')
PY

log "fixtures ready"
